using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PerpTool.Types
{
    public enum AttributeFlags : long
    {
        player,
        invulnerable,
        item,
        onePerRobot,
        activeModule,
        fittingCapacityModifier,
        offensive_module,
        engage_combat,
        self_effect,
        targetIsRobot,
        nonStackable,
        alwaysStackable,
        gang_assist_module,
        primary_locked_target,
        self_target,
        small,
        medium,
        large,
        ammo_required,
        passiveModule,
        gangEffect,
        forceOneCycle,
        nonrelocatable,
        deployable,
        consumable,
        delayed_modul,
        pvp_support,
        nonlockable,
        nonattackable,
        usable,
        mainbase,
        nonRecyclable,
        instantActivate,
        undefined_33,
        undefined_34,
        undefined_35,
        undefined_36,
        undefined_37,
        undefined_38,
        undefined_39,
        undefined_40,
        undefined_41,
        undefined_42,
        undefined_43,
        undefined_44,
        undefined_45,
        undefined_46,
        undefined_47,
        undefined_48,
        undefined_49,
        undefined_50,
        undefined_51,
        undefined_52,
        undefined_53,
        undefined_54,
        undefined_55,
        undefined_56,
        undefined_57,
        undefined_58,
        undefined_59,
        undefined_60,
        undefined_61,
        undefined_62,
        NOT_USED,
    }
}
